CREATE TABLE items (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    balance int NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
    ADD COLUMN all_orders JSON,
    ADD COLUMN pending_orders JSON,
    ADD COLUMN fufilled_orders JSON,
    ADD COLUMN total_profit INT,
    ADD COLUMN total_losses INT,
    ADD COLUMN is_admin TINYINT,
    ADD COLUMN is_approved TINYINT,
    ADD COLUMN is_blocked TINYINT,
    ADD COLUMN connections JSON,
    ADD COLUMN grof_points INT,

ALTER TABLE users ADD COLUMN role VARCHAR(190) NOT NULL;

CREATE TABLE cart(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
role VARCHAR(190) NOT NULL,
email VARCHAR(190) NOT NULL,
total_order_amount BIGINT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN phone_number VARCHAR(20);
ALTER TABLE users ADD COLUMN role VARCHAR(50) DEFAULT 'student';
ALTER TABLE users ADD COLUMN address VARCHAR(190);
